
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xa3\x1d\xf5]\x8c=s\xceM\x89\xa4\x91X\xe7$\x12'
    
_lr_action_items = {'STRING':([0,1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,],[3,-14,-9,-10,-11,-7,3,3,3,-8,-3,-15,3,3,3,3,-2,3,3,-12,-13,-4,3,3,3,3,3,-16,-6,-5,-17,]),'KEYWORD':([0,1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,],[4,-14,-9,-10,-11,-7,4,4,4,-8,-3,-15,4,4,4,4,-2,4,4,-12,-13,-4,4,4,4,4,4,-16,-6,-5,-17,]),')':([1,2,3,4,6,11,12,13,17,19,20,23,24,25,28,29,32,33,],[-14,-9,-10,-11,-7,-8,-3,-15,23,-2,25,-12,-13,-4,32,33,-6,-5,]),'(':([0,1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,],[5,-14,-9,-10,-11,-7,5,5,5,-8,-3,-15,5,5,5,5,-2,5,5,-12,-13,-4,5,5,5,5,5,-16,-6,-5,-17,]),'FLOAT':([0,1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,],[2,-14,-9,-10,-11,-7,2,2,2,-8,-3,-15,2,2,2,2,-2,2,2,-12,-13,-4,2,2,2,2,2,-16,-6,-5,-17,]),'defn':([5,],[15,]),'BRACKET':([0,1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,],[7,-14,-9,-10,-11,-7,7,7,7,-8,-3,-15,7,7,7,7,-2,7,7,-12,-13,-4,7,7,7,7,7,-16,-6,-5,-17,]),'SQBRACKET':([0,1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,],[8,-14,-9,-10,-11,-7,8,8,8,-8,-3,-15,8,8,8,8,-2,8,8,-12,-13,-4,8,8,8,8,8,-16,-6,-5,-17,]),'INTEGER':([0,1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,],[11,-14,-9,-10,-11,-7,11,11,11,-8,-3,-15,11,11,11,11,-2,11,11,-12,-13,-4,11,11,11,11,11,-16,-6,-5,-17,]),'[':([21,],[27,]),']':([1,2,3,4,6,11,12,13,18,19,23,24,25,27,30,32,33,],[-14,-9,-10,-11,-7,-8,-3,-15,24,-2,-12,-13,-4,31,34,-6,-5,]),'ID':([0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,],[13,-14,-9,-10,-11,14,-7,13,13,13,-8,-3,-15,13,21,13,13,13,-2,13,13,-12,-13,-4,13,13,13,13,13,-16,-6,-5,-17,]),'loop':([5,],[16,]),'$end':([1,2,3,4,6,9,10,11,12,13,19,23,24,25,32,33,],[-14,-9,-10,-11,-7,-1,0,-8,-3,-15,-2,-12,-13,-4,-6,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr_list':([0,7,8,14,22,26,27,],[9,17,18,20,28,29,30,]),'idname':([0,7,8,9,14,16,17,18,20,22,26,27,28,29,30,],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]),'vector':([21,],[26,]),'atom':([0,7,8,9,14,16,17,18,20,22,26,27,28,29,30,],[6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,]),'input':([0,],[10,]),'expression':([0,7,8,9,14,16,17,18,20,22,26,27,28,29,30,],[12,12,12,19,12,22,19,19,19,12,12,12,19,19,19,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> expr_list','input',1,'p_input','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',25),
  ('expr_list -> expr_list expression','expr_list',2,'p_expr_list','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',29),
  ('expr_list -> expression','expr_list',1,'p_expr_list','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',30),
  ('expression -> ( ID expr_list )','expression',4,'p_expression','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',38),
  ('expression -> ( defn ID vector expr_list )','expression',6,'p_expression','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',39),
  ('expression -> ( loop expression expr_list )','expression',5,'p_expression','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',40),
  ('expression -> atom','expression',1,'p_expression','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',41),
  ('atom -> INTEGER','atom',1,'p_atom','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',53),
  ('atom -> FLOAT','atom',1,'p_atom','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',54),
  ('atom -> STRING','atom',1,'p_atom','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',55),
  ('atom -> KEYWORD','atom',1,'p_atom','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',56),
  ('atom -> BRACKET expr_list )','atom',3,'p_atom','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',57),
  ('atom -> SQBRACKET expr_list ]','atom',3,'p_atom','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',58),
  ('atom -> idname','atom',1,'p_atom','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',59),
  ('idname -> ID','idname',1,'p_idname','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',68),
  ('vector -> [ ]','vector',2,'p_vector','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',73),
  ('vector -> [ expr_list ]','vector',3,'p_vector','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',74),
  ('list -> ( )','list',2,'p_list','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',86),
  ('list -> ( expr_list )','list',3,'p_list','c:\\DropBox\\Workspaces\\GitHub\\ClojureInterpreter\\LISPparser.py',87),
]
